# Cloudflare Workers 部署配置
name = "tempmailhub"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# 环境变量 (可选，可在部署后在Cloudflare Dashboard中设置)
# [vars]
# TEMPMAILHUB_API_KEY = ""  # 设置API Key启用认证

# 部署环境
[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" } 